### ISSUE TITLE
how does the negative sampling work?

### ISSUE THREAD

**Issue by marcoleewow** [kefirski/pytorch_NEG_loss#3]
Hi, sorry for a newbie question, how does the negative sampling work in neg.py, in particular [line 69](https://github.com/analvikingur/pytorch_NEG_loss/blob/eb8476d9dc49579b5ac51c966fccda121cd06730/NEG_loss/neg.py#L69)? I cannot find any documentations on calling neg in nn.embedding...

**Comment by kefirski** [comment]
You can find good explanation of idea behind word2vec [here](http://mccormickml.com/2016/04/19/word2vec-tutorial-the-skip-gram-model/) and [here](http://mccormickml.com/2017/01/11/word2vec-tutorial-part-2-negative-sampling/)

**Comment by marcoleewow** [comment]
Hi, sorry if I did not make it clear, I understand how negative sampling works, but I just want to know what exactly happens when you call neg() on nn.embedding, AFAIK there is no documentation on it.

**Comment by marcoleewow** [comment]
Wow I feel dumb now, neg() is a member function of torch.tensor, not nn.embedding...Sorry for the stupid question.
